import { strict as assert } from "node:assert";
import { describe, it } from "node:test";

import { assertLocalE2eEnvironment } from "./local-safety";
import {
  buildLocalApplicationEnvironment,
  normalizeSupabaseStatus,
  parseSupabaseStatusEnv,
} from "./env";

const safeEnvironment = {
  E2E_TEST_MODE: "1",
  NEXT_PUBLIC_SUPABASE_URL: "http://127.0.0.1:54321",
  DATABASE_URL: "postgresql://postgres:postgres@127.0.0.1:54322/postgres",
};

describe("assertLocalE2eEnvironment", () => {
  it("accepts the local Supabase API and database", () => {
    assert.doesNotThrow(() => assertLocalE2eEnvironment(safeEnvironment));
  });

  it("requires explicit E2E mode", () => {
    assert.throws(
      () =>
        assertLocalE2eEnvironment({
          ...safeEnvironment,
          E2E_TEST_MODE: undefined,
        }),
      /E2E_TEST_MODE must be 1/,
    );
  });

  it("rejects hosted or HTTPS Supabase URLs", () => {
    for (const url of [
      "https://abcdefgh.supabase.co",
      "https://127.0.0.1:54321",
      "http://staging.example.test:54321",
    ]) {
      assert.throws(
        () =>
          assertLocalE2eEnvironment({
            ...safeEnvironment,
            NEXT_PUBLIC_SUPABASE_URL: url,
          }),
        /NEXT_PUBLIC_SUPABASE_URL must target|NEXT_PUBLIC_SUPABASE_URL must be http/,
      );
    }
  });

  it("rejects non-local API and database ports", () => {
    assert.throws(
      () =>
        assertLocalE2eEnvironment({
          ...safeEnvironment,
          NEXT_PUBLIC_SUPABASE_URL: "http://127.0.0.1:54322",
        }),
      /NEXT_PUBLIC_SUPABASE_URL must be http/,
    );
    assert.throws(
      () =>
        assertLocalE2eEnvironment({
          ...safeEnvironment,
          DATABASE_URL: "postgresql://postgres:postgres@127.0.0.1:54321/postgres",
        }),
      /DATABASE_URL must target/,
    );
  });

  it("requires both URLs", () => {
    assert.throws(
      () =>
        assertLocalE2eEnvironment({
          E2E_TEST_MODE: "1",
        }),
      /Missing NEXT_PUBLIC_SUPABASE_URL/,
    );
  });
});

describe("Supabase status environment", () => {
  const legacyOutput = `
# generated by supabase status -o env
API_URL="http://127.0.0.1:54321"
ANON_KEY="publishable=with=equals"
SERVICE_ROLE_KEY="secret-value"
DB_URL="postgresql://postgres:postgres@127.0.0.1:54322/postgres"
`;

  it("parses quoted values without evaluating shell syntax", () => {
    assert.deepEqual(parseSupabaseStatusEnv(legacyOutput), {
      API_URL: "http://127.0.0.1:54321",
      ANON_KEY: "publishable=with=equals",
      SERVICE_ROLE_KEY: "secret-value",
      DB_URL: "postgresql://postgres:postgres@127.0.0.1:54322/postgres",
    });
  });

  it("normalizes legacy status names", () => {
    assert.deepEqual(normalizeSupabaseStatus(legacyOutput), {
      NEXT_PUBLIC_SUPABASE_URL: "http://127.0.0.1:54321",
      NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: "publishable=with=equals",
      SUPABASE_SECRET_KEY: "secret-value",
      DATABASE_URL: "postgresql://postgres:postgres@127.0.0.1:54322/postgres",
    });
  });

  it("supports current explicit key names and fixed stub endpoints", () => {
    const environment = buildLocalApplicationEnvironment(`
API_URL=http://localhost:54321
PUBLISHABLE_KEY=sb_publishable_local
SECRET_KEY=sb_secret_local
DATABASE_URL=postgresql://postgres:postgres@localhost:54322/postgres
`);

    assert.deepEqual(environment, {
      NEXT_PUBLIC_SUPABASE_URL: "http://localhost:54321",
      NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: "sb_publishable_local",
      SUPABASE_SECRET_KEY: "sb_secret_local",
      DATABASE_URL: "postgresql://postgres:postgres@localhost:54322/postgres",
      NEXT_PUBLIC_SITE_URL: "http://127.0.0.1:3100",
      E2E_TEST_MODE: "1",
      ANILIST_GRAPHQL_URL: "http://127.0.0.1:4100/anilist/graphql",
      OPENAI_BASE_URL: "http://127.0.0.1:4100/openai/v1",
      OPENAI_API_KEY: "e2e-placeholder",
    });
  });

  it("reports missing status values without exposing secrets", () => {
    assert.throws(
      () => normalizeSupabaseStatus("API_URL=http://127.0.0.1:54321"),
      /missing the publishable key/,
    );
  });
});
