-- Preserve recommendation display order generated by adventurous sampling

ALTER TABLE public.recommendations
  ADD COLUMN IF NOT EXISTS position integer;

WITH ranked AS (
  SELECT
    id,
    row_number() OVER (
      PARTITION BY run_id
      ORDER BY final_score DESC, created_at ASC, id ASC
    ) - 1 AS next_position
  FROM public.recommendations
)
UPDATE public.recommendations AS recommendations
SET position = ranked.next_position
FROM ranked
WHERE recommendations.id = ranked.id
  AND recommendations.position IS NULL;

ALTER TABLE public.recommendations
  ALTER COLUMN position SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS recommendations_run_position_unique
  ON public.recommendations (run_id, position);

CREATE INDEX IF NOT EXISTS recommendations_run_position_idx
  ON public.recommendations (run_id, position);
